export const ca_translations = {
    general: {
        subtitle: 'Mode de Joc',
        playerCodeLabel: 'Codis de jugador',
    },
    server: {
      roomNotFound: 'Sala no trobada.',
      gameAlreadyStartedInRoom: 'La partida ja ha començat en aquesta sala.',
      roomIsFull: 'La sala està plena.',
      gameAlreadyStarted: 'La partida ja ha començat.',
      onlyHostCanStart: 'Només l\'amfitrió pot iniciar la partida.',
      treacheryRequiresAtLeast4Players: 'Treachery requereix almenys 4 jugadors.',
      gameStartedAndRolesDealt: 'La partida ha començat i s\'han repartit els rols d\'identitat.',
      playerNotFoundInRoom: 'Jugador no trobat a la sala.',
      gameNotStartedYet: 'La partida encara no ha començat.',
    },
    home: {
      eyebrow: 'Funció',
      treacheryTitle: 'Treachery',
      description: 'Benvingut al teu espai multijugador de taula. Crea sales privades, convida amics i llança formats socials.',
      primaryCta: 'Obrir Nou Treachery',
      secondaryCta: 'Unir-se amb codi de sala',
      moreTitle: 'Més modes i funcions en el futur!',
      moreDescription: 'Mira aquest espai per a propers jocs i funcions.',
      },
    treachery: {
      homeTitle: 'Treachery',
      homeDescription: 'Tria quants jugadors participen i quanta vida inicial tindran.',
      description: 'Crea una sala, comparteix el codi i revela la teva identitat quan comenci el joc.',
      homePrimaryCta: 'Obrir Nou Treachery',    
      homeSecondaryCta: 'Unir-se amb codi de sala',
      playerCountLabel: 'Nombre de jugadors',
      startingLifeLabel: 'Vides inicials',
      startButton: 'Iniciar comptador',
      counterTitle: 'Comptador de vides',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
      message_signal: 'Crea una sala o uneix-te a una amb un codi de sala.',
      createButton: 'Crear sala',
      joinButton: 'Unir-se a sala',
      roomCodeLabel: 'Codi de sala',
      roomPlayerCode: 'El teu codi de jugador en aquest navegador:',
      roomRequiredPlayers: 'Es requereixen almenys 4 jugadors per començar Treachery.',
      refreshButton: 'Refrescar',
      startGameButton: 'Iniciar joc',
      leaveRoomButton: 'Sortir de la sala',
      dealingMessage: 'Repartint cartes, si us plau espera...',
        waitingPlayersMessage: 'Esperant jugadors. Comparteix el codi de sala perquè altres puguin unir-se.',
   
    },
    lifeCounter: {
      homeTitle: 'Comptador de vides',
      homeDescription: 'sdsdsds',
      description: 'Tria quants jugadors participen i quanta vida inicial tindran.', 
      homePrimaryCta:'Obrir comptador de vida',
      playerCountLabel: 'Nombre de jugadors',
      startingLifeLabel: 'Vides inicials',
      startButton: 'Iniciar comptador',
      counterTitle: 'Comptador de vides',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
    },
};