export const ca_translations = {
    general: {
        playerCodeLabel: 'Codis de jugador',
    },
    server: {
      roomNotFound: 'Sala no trobada.',
      gameAlreadyStartedInRoom: 'La partida ja ha començat en aquesta sala.',
      roomIsFull: 'La sala està plena.',
      gameAlreadyStarted: 'La partida ja ha començat.',
      onlyHostCanStart: 'Només l\'amfitrió pot iniciar la partida.',
      treacheryRequiresAtLeast4Players: 'Treachery requereix almenys 4 jugadors.',
      gameStartedAndRolesDealt: 'La partida ha començat i s\'han repartit els rols d\'identitat.',
      kingdomRequiresFiveToSevenPlayers: 'Kingdom requereix entre 5 i 7 jugadors.',
      playerNotFoundInRoom: 'Jugador no trobat a la sala.',
      gameNotStartedYet: 'La partida encara no ha començat.',
    },
    home: {
      eyebrow: 'Mode de Joc',
      treacheryTitle: 'Treachery',
      description: 'Benvingut al teu espai multijugador de taula. Crea sales privades, convida amics i llança formats socials.',
      primaryCta: 'Obrir Nou Treachery',
      secondaryCta: 'Unir-se amb codi de sala',
      moreTitle: 'MTG Play2Gether',
      moreDescription: 'Més modes i funcions en el futur! Mira aquest espai per a propers jocs i funcions.',
      },
    treachery: {
      homeTitle: 'Treachery',
      homeDescription: 'Crea sales, reparteix els rols, fes servir les teves habilitats i traiciona als teus rivals.',
      description: 'Crea una sala, comparteix el codi i revela la teva identitat quan comenci el joc.',
      homePrimaryCta: 'Obrir Nou Treachery',    
      homeSecondaryCta: 'Unir-se amb codi de sala',
      playerCountLabel: 'Nombre de jugadors',
      startingLifeLabel: 'Vides inicials',
      startButton: 'Iniciar comptador',
      counterTitle: 'Comptador de vides',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
      message_signal: 'Crea una sala o uneix-te a una amb un codi de sala.',
      createButton: 'Crear sala',
      joinButton: 'Unir-se a sala',
      roomCodeLabel: 'Codi de sala',
      roomPlayerCode: 'El teu codi de jugador en aquest navegador:',
      roomRequiredPlayers: 'Es requereixen almenys 4 jugadors per començar Treachery.',
      refreshButton: 'Refrescar',
      startGameButton: 'Iniciar joc',
      leaveRoomButton: 'Sortir de la sala',
      dealingMessage: 'Repartint cartes, si us plau espera...',
      waitingPlayersMessage: 'Esperant jugadors. Comparteix el codi de sala perquè altres puguin unir-se.',
      notSet: 'Sense assignar',
      youTag: 'Tu',
      hostTag: 'Amfitrió',
      bufferingLabel: 'Processant',
      copyRoomCodeSuccess: 'Codi de sala "{code}" copiat al porta-retalls.',
      copyRoomCodeError: 'Error en copiar el codi de sala al porta-retalls.',
      identityLabel: 'Identitat',
      teamLabel: 'Equip',
      rulingsLabel: 'Regles',
      refreshRoomButton: 'Refrescar sala',
      roleCardLoadedMessage: 'Carta de rol carregada. Mantén-la en privat durant la partida.',
      leaveRoomBrowserMessage: 'Has sortit de la sala en aquest navegador. Pots crear-ne una altra o unir-te a una altra.',
      localPlayerDataRemovedMessage: 'Les dades del jugador local s\'han eliminat d\'aquest navegador.',
      debugRoleCardPreviewMessage: 'Vista prèvia de carta de rol activa des del paràmetre roleCard.title.',
      roomCreatedMessage: 'Sala creada. Comparteix el codi de sala perquè altres puguin unir-se.',
      typeRoomCodeBeforeJoinMessage: 'Escriu un codi de sala abans d\'unir-te.',
      joinedRoomMessage: 'T\'has unit a la sala. Espera que l\'amfitrió iniciï la partida.',
      joinRoomBeforeStartMessage: 'Uneix-te a una sala abans d\'iniciar una partida.',
      missingRoomOrPlayerCodeMessage: 'Falta el codi de sala o de jugador a l\'emmagatzematge del navegador.',
      requestFailedMessage: 'La sol·licitud ha fallat.',
      gameStartedFallbackMessage: 'La partida ha començat.',
      roleSummaryPrefix: 'Rols',
      typeRoomCodePrompt: 'Escriu el codi de sala per unir-te:',
      unexpectedErrorMessage: 'Error inesperat',
      errorPrefix: 'Error',
      roleCardArtworkAlt: 'Il·lustració de carta de rol',
   
    },
    kingdom: {
      homeTitle: 'Kingdom',
      homeDescription: 'Crea una sala, comparteix el codi i revela el teu rol quan comenci la partida.',
      description: 'Crea una sala, comparteix el codi i revela el teu rol quan comenci la partida.',
      homePrimaryCta: 'Obrir Nou Kingdom',    
      homeSecondaryCta: 'Unir-se amb codi de sala',
      createButton: 'Crear sala',
      joinButton: 'Unir-se a sala',
      roomCodeLabel: 'Codi de sala',
      roomPlayerCode: 'El teu codi de jugador en aquest navegador:',
      roomRequiredPlayers: 'Kingdom requereix entre 5 i 7 jugadors per començar.',
      refreshButton: 'Refrescar',
      startGameButton: 'Iniciar joc',
      leaveRoomButton: 'Sortir de la sala',
      dealingMessage: 'Repartint cartes, si us plau espera...',
      waitingPlayersMessage: 'Esperant jugadors. Comparteix el codi de sala perquè altres puguin unir-se.',
      notSet: 'Sense assignar',
      youTag: 'Tu',
      hostTag: 'Amfitrió',
      bufferingLabel: 'Processant',
      copyRoomCodeSuccess: 'Codi de sala "{code}" copiat al porta-retalls.',
      copyRoomCodeError: 'Error en copiar el codi de sala al porta-retalls.',
      identityLabel: 'Identitat',
      teamLabel: 'Equip',
      rulingsLabel: 'Regles',
      refreshRoomButton: 'Refrescar sala',
      roleCardLoadedMessage: 'Carta de rol carregada. Mantén-la en privat durant la partida.',
      leaveRoomBrowserMessage: 'Has sortit de la sala en aquest navegador. Pots crear-ne una altra o unir-te a una altra.',
      localPlayerDataRemovedMessage: 'Les dades del jugador local s\'han eliminat d\'aquest navegador.',
      debugRoleCardPreviewMessage: 'Vista prèvia de carta de rol activa des del paràmetre roleCard.title.',
      roomCreatedMessage: 'Sala creada. Comparteix el codi de sala perquè altres puguin unir-se.',
      typeRoomCodeBeforeJoinMessage: 'Escriu un codi de sala abans d\'unir-te.',
      joinedRoomMessage: 'T\'has unit a la sala. Espera que l\'amfitrió iniciï la partida.',
      joinRoomBeforeStartMessage: 'Uneix-te a una sala abans d\'iniciar una partida.',
      missingRoomOrPlayerCodeMessage: 'Falta el codi de sala o de jugador a l\'emmagatzematge del navegador.',
      requestFailedMessage: 'La sol·licitud ha fallat.',
      gameStartedFallbackMessage: 'La partida ha començat.',
      roleSummaryPrefix: 'Rols',
      typeRoomCodePrompt: 'Escriu el codi de sala per unir-te:',
      unexpectedErrorMessage: 'Error inesperat',
      errorPrefix: 'Error',
    },
    lifeCounter: {
      homeTitle: 'Comptador de vides',
      homeDescription: 'sdsdsds',
      description: 'Tria quants jugadors participen i quanta vida inicial tindran.', 
      homePrimaryCta:'Obrir comptador de vida',
      playerCountLabel: 'Nombre de jugadors',
      startingLifeLabel: 'Vides inicials',
      startButton: 'Iniciar comptador',
      counterTitle: 'Comptador de vides',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
    },
};