export const en_translations = {
    general: {
        subtitle: 'Game Mode',
        playerCodeLabel: 'Player Codes',
    },
    server: {
        roomNotFound: 'Room not found.',
        gameAlreadyStartedInRoom: 'Game already started in this room.',
        roomIsFull: 'Room is full.',
        gameAlreadyStarted: 'Game already started.',
        onlyHostCanStart: 'Only host can start the game.',
        treacheryRequiresAtLeast4Players: 'Treachery requires at least 4 players.',
        gameStartedAndRolesDealt: 'Game started and identity roles were dealt.',
        playerNotFoundInRoom: 'Player not found in room.',
        gameNotStartedYet: 'Game not started yet.',
    },
    home: {
        eyebrow: 'Feature',
        moreTitle: 'More game modes and features in the future!',
        moreDescription: 'Watch this space for upcoming games and features.',},
    treachery: {
        homeTitle: 'Treachery',
        homeDescription: 'Choose how many players are participating and their starting life total.',
        description: 'Create a room, share the code, and reveal your identity when the game starts.',
        homePrimaryCta: 'Open New Treachery',    
        homeSecondaryCta: 'Join With Room Code',
        playerCountLabel: 'Number of players',
        startingLifeLabel: 'Starting life',
        startButton: 'Start counter',
        counterTitle: 'Life Counter',
        resetButton: 'Reset',
        playerName: 'Player',
        message_signal: 'Create a room or join one with a room code.',
        createButton: 'Create Room',
        joinButton: 'Join Room',
        roomCodeLabel: 'Room Code',
        roomPlayerCode: 'Your player code in this browser:',
        roomRequiredPlayers: 'At least 4 players are required to start Treachery.',
        refreshButton: 'Refresh',
        startGameButton: 'Start Game',
        leaveRoomButton: 'Leave Room',
        dealingMessage: 'The roles are being dealt right now, please wait...',
        waitingPlayersMessage: 'Waiting for players. Share the room code so others can join.'
    },
    lifeCounter: {
        homeTitle: 'Life Counter',
        homeDescription:'sdsdsdsdsds',
        description: 'Choose how many players are participating and their starting life total.',
        homePrimaryCta: 'Open Life Counter',
        playerCountLabel: 'Number of players',
        startingLifeLabel: 'Starting life',
        startButton: 'Start counter',
        counterTitle: 'Life Counter',
        resetButton: 'Reset',
        playerName: 'Player',
    },
};