export const en_translations = {
    general: {
        playerCodeLabel: 'Player Codes',
    },
    server: {
        roomNotFound: 'Room not found.',
        gameAlreadyStartedInRoom: 'Game already started in this room.',
        roomIsFull: 'Room is full.',
        gameAlreadyStarted: 'Game already started.',
        onlyHostCanStart: 'Only host can start the game.',
        treacheryRequiresAtLeast4Players: 'Treachery requires at least 4 players.',
        gameStartedAndRolesDealt: 'Game started and identity roles were dealt.',
        kingdomRequiresFiveToSevenPlayers: 'Kingdom requires between 5 and 7 players.',
        playerNotFoundInRoom: 'Player not found in room.',
        gameNotStartedYet: 'Game not started yet.',
    },
    home: {
        eyebrow: 'Game Mode',
        moreTitle: 'MTG Play2Gether',
        moreDescription: 'More game modes and features in the future! Watch this space for upcoming games and features.',},
    treachery: {
        homeTitle: 'Treachery',
        homeDescription: 'Create rooms, deal roles, use your abilities, and betray your rivals.',
        description: 'Create a room, share the code, and reveal your identity when the game starts.',
        homePrimaryCta: 'Open New Treachery',    
        homeSecondaryCta: 'Join With Room Code',
        playerCountLabel: 'Number of players',
        startingLifeLabel: 'Starting life',
        startButton: 'Start counter',
        counterTitle: 'Life Counter',
        resetButton: 'Reset',
        playerName: 'Player',
        message_signal: 'Create a room or join one with a room code.',
        createButton: 'Create Room',
        joinButton: 'Join Room',
        roomCodeLabel: 'Room Code',
        roomPlayerCode: 'Your player code in this browser:',
        roomRequiredPlayers: 'At least 4 players are required to start Treachery.',
        refreshButton: 'Refresh',
        startGameButton: 'Start Game',
        leaveRoomButton: 'Leave Room',
        dealingMessage: 'The roles are being dealt right now, please wait...',
        waitingPlayersMessage: 'Waiting for players. Share the room code so others can join.',
        notSet: 'Not set',
        youTag: 'You',
        hostTag: 'Host',
        bufferingLabel: 'Buffering',
        copyRoomCodeSuccess: 'Room code "{code}" copied to clipboard!',
        copyRoomCodeError: 'Error copying room code to clipboard.',
        identityLabel: 'Identity',
        teamLabel: 'Team',
        rulingsLabel: 'Rulings',
        refreshRoomButton: 'Refresh Room',
        roleCardLoadedMessage: 'Role card loaded. Keep it private during the game.',
        leaveRoomBrowserMessage: 'You left the room on this browser. You can create or join another one.',
        localPlayerDataRemovedMessage: 'Local player data removed from this browser.',
        debugRoleCardPreviewMessage: 'Debug role card preview active from query param roleCard.title.',
        roomCreatedMessage: 'Room created. Share the room code so others can join.',
        typeRoomCodeBeforeJoinMessage: 'Type a room code before joining.',
        joinedRoomMessage: 'Joined room. Wait for host to start the game.',
        joinRoomBeforeStartMessage: 'Join a room before starting a game.',
        missingRoomOrPlayerCodeMessage: 'Missing room or player code in browser storage.',
        requestFailedMessage: 'Request failed.',
        gameStartedFallbackMessage: 'Game started.',
        roleSummaryPrefix: 'Roles',
        typeRoomCodePrompt: 'Type the room code to join:',
        unexpectedErrorMessage: 'Unexpected error',
        errorPrefix: 'Error',
        roleCardArtworkAlt: 'Role card artwork',
    },
    kingdom: {
        homeTitle: 'Kingdom',
        description: 'Create a room, share the code, and reveal your role when the game starts.',
        createButton: 'Create Room',
        joinButton: 'Join Room',
        roomCodeLabel: 'Room Code',
        roomPlayerCode: 'Your player code in this browser:',
        roomRequiredPlayers: 'Kingdom requires between 5 and 7 players to start.',
        refreshButton: 'Refresh',
        startGameButton: 'Start Game',
        leaveRoomButton: 'Leave Room',
        dealingMessage: 'The roles are being dealt right now, please wait...',
        waitingPlayersMessage: 'Waiting for players. Share the room code so others can join.',
        notSet: 'Not set',
        youTag: 'You',
        hostTag: 'Host',
        bufferingLabel: 'Buffering',
        copyRoomCodeSuccess: 'Room code "{code}" copied to clipboard!',
        copyRoomCodeError: 'Error copying room code to clipboard.',
        identityLabel: 'Identity',
        teamLabel: 'Team',
        rulingsLabel: 'Rulings',
        refreshRoomButton: 'Refresh Room',
        roleCardLoadedMessage: 'Role card loaded. Keep it private during the game.',
        leaveRoomBrowserMessage: 'You left the room on this browser. You can create or join another one.',
        localPlayerDataRemovedMessage: 'Local player data removed from this browser.',
        debugRoleCardPreviewMessage: 'Debug role card preview active from query param roleCard.title.',
        roomCreatedMessage: 'Room created. Share the room code so others can join.',
        typeRoomCodeBeforeJoinMessage: 'Type a room code before joining.',
        joinedRoomMessage: 'Joined room. Wait for host to start the game.',
        joinRoomBeforeStartMessage: 'Join a room before starting a game.',
        missingRoomOrPlayerCodeMessage: 'Missing room or player code in browser storage.',
        requestFailedMessage: 'Request failed.',
        gameStartedFallbackMessage: 'Game started.',
        roleSummaryPrefix: 'Roles',
        typeRoomCodePrompt: 'Type the room code to join:',
        unexpectedErrorMessage: 'Unexpected error',
        errorPrefix: 'Error',
    },
    lifeCounter: {
        homeTitle: 'Life Counter',
        homeDescription:'sdsdsdsdsds',
        description: 'Choose how many players are participating and their starting life total.',
        homePrimaryCta: 'Open Life Counter',
        playerCountLabel: 'Number of players',
        startingLifeLabel: 'Starting life',
        startButton: 'Start counter',
        counterTitle: 'Life Counter',
        resetButton: 'Reset',
        playerName: 'Player',
    },
};