export const es_translations = {
    general: {      
        subtitle: 'Modo de Juego',
        playerCodeLabel: 'Códigos de jugador',
    },
    server: {
      roomNotFound: 'Sala no encontrada.',
      gameAlreadyStartedInRoom: 'La partida ya ha empezado en esta sala.',
      roomIsFull: 'La sala está llena.',
      gameAlreadyStarted: 'La partida ya ha empezado.',
      onlyHostCanStart: 'Solo el anfitrión puede iniciar la partida.',
      treacheryRequiresAtLeast4Players: 'Treachery requiere al menos 4 jugadores.',
      gameStartedAndRolesDealt: 'La partida ha comenzado y se han repartido los roles de identidad.',
      playerNotFoundInRoom: 'Jugador no encontrado en la sala.',
      gameNotStartedYet: 'La partida aún no ha empezado.',
    },
    home: {
      eyebrow: 'Función',
      moreTitle: '¡Más modos y funciones en el futuro!',
      moreDescription: 'Mira este espacio para próximos juegos y funciones.',
    },
    treachery: {
      homeTitle: 'Treachery',
      homeDescription: 'Elige cuántos jugadores participan y cuánta vida inicial tendrán.',
      description: 'Crea una sala, comparte el código y revela tu identidad cuando comience el juego.',
      homePrimaryCta: 'Abrir Nuevo Treachery',    
      homeSecondaryCta: 'Unirse con código de sala',
      playerCountLabel: 'Número de jugadores',
      startingLifeLabel: 'Vidas iniciales',
      startButton: 'Iniciar contador',
      counterTitle: 'Contador de vidas',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
      message_signal: 'Crea una sala o únete a una con un código de sala.',
      createButton: 'Crear sala',
      joinButton : 'Unirse a sala',
      roomCodeLabel: 'Código de sala',
      roomPlayerCode: 'Tu código de jugador en este navegador:',
      roomRequiredPlayers: 'Se requieren al menos 4 jugadores para comenzar Treachery.',
      refreshButton: 'Actualizar',
      startGameButton: 'Iniciar juego',
      leaveRoomButton: 'Salir de la sala',
      dealingMessage: 'Repartiendo cartas, por favor espera...',
      waitingPlayersMessage: 'Esperando jugadores. Comparte el código de sala para que otros puedan unirse.',
    },
    lifeCounter: {
      homeTitle: 'Contador de vidas',
      homeDescription: 'asasasas',
      description: 'Elige cuántos jugadores participan y cuánta vida inicial tendrán.',
      homePrimaryCta: 'Abrir contador de vida',
      playerCountLabel: 'Número de jugadores',
      startingLifeLabel: 'Vidas iniciales',
      startButton: 'Iniciar contador',
      counterTitle: 'Contador de vidas',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
    },
};