export const es_translations = {
    general: {      
        playerCodeLabel: 'Códigos de jugador',
    },
    server: {
      roomNotFound: 'Sala no encontrada.',
      gameAlreadyStartedInRoom: 'La partida ya ha empezado en esta sala.',
      roomIsFull: 'La sala está llena.',
      gameAlreadyStarted: 'La partida ya ha empezado.',
      onlyHostCanStart: 'Solo el anfitrión puede iniciar la partida.',
      treacheryRequiresAtLeast4Players: 'Treachery requiere al menos 4 jugadores.',
      gameStartedAndRolesDealt: 'La partida ha comenzado y se han repartido los roles de identidad.',
      kingdomRequiresFiveToSevenPlayers: 'Kingdom requiere entre 5 y 7 jugadores.',
      playerNotFoundInRoom: 'Jugador no encontrado en la sala.',
      gameNotStartedYet: 'La partida aún no ha empezado.',
    },
    home: {
      eyebrow: 'Modo de Juego',
      moreTitle: 'MTG Play2Gether',
      moreDescription: '¡Más modos y funciones en el futuro! Mira este espacio para próximos juegos y funciones.',
    },
    treachery: {
      homeTitle: 'Treachery',
      homeDescription: 'Crea salas, reparte roles, usa tus habilidades y traiciona a tus rivales.',
      description: 'Crea una sala, comparte el código y revela tu identidad cuando comience el juego.',
      homePrimaryCta: 'Abrir Nuevo Treachery',    
      homeSecondaryCta: 'Unirse con código de sala',
      playerCountLabel: 'Número de jugadores',
      startingLifeLabel: 'Vidas iniciales',
      startButton: 'Iniciar contador',
      counterTitle: 'Contador de vidas',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
      message_signal: 'Crea una sala o únete a una con un código de sala.',
      createButton: 'Crear sala',
      joinButton : 'Unirse a sala',
      roomCodeLabel: 'Código de sala',
      roomPlayerCode: 'Tu código de jugador en este navegador:',
      roomRequiredPlayers: 'Se requieren al menos 4 jugadores para comenzar Treachery.',
      refreshButton: 'Actualizar',
      startGameButton: 'Iniciar juego',
      leaveRoomButton: 'Salir de la sala',
      dealingMessage: 'Repartiendo cartas, por favor espera...',
      waitingPlayersMessage: 'Esperando jugadores. Comparte el código de sala para que otros puedan unirse.',
      notSet: 'Sin asignar',
      youTag: 'Tú',
      hostTag: 'Anfitrión',
      bufferingLabel: 'Procesando',
      copyRoomCodeSuccess: 'Código de sala "{code}" copiado al portapapeles.',
      copyRoomCodeError: 'Error al copiar el código de sala al portapapeles.',
      identityLabel: 'Identidad',
      teamLabel: 'Equipo',
      rulingsLabel: 'Reglas',
      refreshRoomButton: 'Actualizar sala',
      roleCardLoadedMessage: 'Carta de rol cargada. Mantenla en privado durante la partida.',
      leaveRoomBrowserMessage: 'Has salido de la sala en este navegador. Puedes crear otra o unirte a otra.',
      localPlayerDataRemovedMessage: 'Los datos del jugador local se han eliminado de este navegador.',
      debugRoleCardPreviewMessage: 'Vista previa de carta de rol activa desde el parámetro roleCard.title.',
      roomCreatedMessage: 'Sala creada. Comparte el código de sala para que otros puedan unirse.',
      typeRoomCodeBeforeJoinMessage: 'Escribe un código de sala antes de unirte.',
      joinedRoomMessage: 'Te has unido a la sala. Espera a que el anfitrión inicie la partida.',
      joinRoomBeforeStartMessage: 'Únete a una sala antes de iniciar una partida.',
      missingRoomOrPlayerCodeMessage: 'Falta el código de sala o de jugador en el almacenamiento del navegador.',
      requestFailedMessage: 'La solicitud falló.',
      gameStartedFallbackMessage: 'La partida ha comenzado.',
      roleSummaryPrefix: 'Roles',
      typeRoomCodePrompt: 'Escribe el código de sala para unirte:',
      unexpectedErrorMessage: 'Error inesperado',
      errorPrefix: 'Error',
      roleCardArtworkAlt: 'Ilustración de carta de rol',
    },
    kingdom: {
      homeTitle: 'Kingdom',
      homeDescription: 'Crea salas, reparte roles, forma equipos y traiciona a tus rivales.',
      description: 'Crea una sala, comparte el código y revela tu rol cuando comience la partida.',
      homePrimaryCta: 'Abrir Nuevo Kingdom',    
      homeSecondaryCta: 'Unirse con código de sala',
      createButton: 'Crear sala',
      joinButton: 'Unirse a sala',
      roomCodeLabel: 'Código de sala',
      roomPlayerCode: 'Tu código de jugador en este navegador:',
      roomRequiredPlayers: 'Kingdom requiere entre 5 y 7 jugadores para comenzar.',
      refreshButton: 'Actualizar',
      startGameButton: 'Iniciar juego',
      leaveRoomButton: 'Salir de la sala',
      dealingMessage: 'Repartiendo cartas, por favor espera...',
      waitingPlayersMessage: 'Esperando jugadores. Comparte el código de sala para que otros puedan unirse.',
      notSet: 'Sin asignar',
      youTag: 'Tú',
      hostTag: 'Anfitrión',
      bufferingLabel: 'Procesando',
      copyRoomCodeSuccess: 'Código de sala "{code}" copiado al portapapeles.',
      copyRoomCodeError: 'Error al copiar el código de sala al portapapeles.',
      identityLabel: 'Identidad',
      teamLabel: 'Equipo',
      rulingsLabel: 'Reglas',
      refreshRoomButton: 'Actualizar sala',
      roleCardLoadedMessage: 'Carta de rol cargada. Mantenla en privado durante la partida.',
      leaveRoomBrowserMessage: 'Has salido de la sala en este navegador. Puedes crear otra o unirte a otra.',
      localPlayerDataRemovedMessage: 'Los datos del jugador local se han eliminado de este navegador.',
      debugRoleCardPreviewMessage: 'Vista previa de carta de rol activa desde el parámetro roleCard.title.',
      roomCreatedMessage: 'Sala creada. Comparte el código de sala para que otros puedan unirse.',
      typeRoomCodeBeforeJoinMessage: 'Escribe un código de sala antes de unirte.',
      joinedRoomMessage: 'Te has unido a la sala. Espera a que el anfitrión inicie la partida.',
      joinRoomBeforeStartMessage: 'Únete a una sala antes de iniciar una partida.',
      missingRoomOrPlayerCodeMessage: 'Falta el código de sala o de jugador en el almacenamiento del navegador.',
      requestFailedMessage: 'La solicitud falló.',
      gameStartedFallbackMessage: 'La partida ha comenzado.',
      roleSummaryPrefix: 'Roles',
      typeRoomCodePrompt: 'Escribe el código de sala para unirte:',
      unexpectedErrorMessage: 'Error inesperado',
      errorPrefix: 'Error',
    },
    lifeCounter: {
      homeTitle: 'Contador de vidas',
      homeDescription: 'asasasas',
      description: 'Elige cuántos jugadores participan y cuánta vida inicial tendrán.',
      homePrimaryCta: 'Abrir contador de vida',
      playerCountLabel: 'Número de jugadores',
      startingLifeLabel: 'Vidas iniciales',
      startButton: 'Iniciar contador',
      counterTitle: 'Contador de vidas',
      resetButton: 'Reiniciar',
      playerName: 'Jugador',
    },
};